### ISSUE TITLE
Questions about CORS and CSRF config

### ISSUE THREAD

**Issue by vasilaio** [jzheaux/spring-security-tanzu-tuesday-november#2]
Hi @jzheaux,

I have some question about your config on CORS and CSRF.
1. To config CORS, why did [you used](https://youtu.be/P4TI1gLmr-4?t=2499) WebMvcConfigurer instead of customizer (HttpSecurity object) or a CorsConfigurationSource bean?
2. To config CSRF, why did [you used](https://youtu.be/P4TI1gLmr-4?t=2993) ControllerAdvice instead of csrf config + customizer (HttpSecurity object)?

Greate video, btw.

**Comment by jzheaux** [comment]
Hi, @vasilaio, great questions, and I'm glad you liked the video.

1. Mostly because I like the `CorsRegistry` DSL, plus probably a little bit of habit. Both approaches eventually create a `CorsConfigurationSource`, though I believe [Spring MVC will merge `CorsRegistry` with method-level `@CrossOrigin` annotations](https://docs.spring.io/spring-framework/docs/current/reference/html/web.html#mvc-cors-processing).

2. I used `ControllerAdvice` since I wanted the method to be invoked after each controller method and it's very little code. Having it as a separate class made it easy to remove in the middle of the demo.

There's no Spring Security CSRF config for writing the token to a header, but you could do the following in the DSL:

```java
http
    .headers((headers) -> headers
        .addHeaderWriter((request, response) -> {
            CsrfToken token = (CsrfToken) request.getAttribute(CsrfToken.class.getName());
            response.setHeader(token.getHeaderName(), token.getToken());
        })
    );
```
